package cn.zhanghl.util;
import java.sql.*;
public class DBUtil {
    public static Connection getConn() {
        Connection conn = null;

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn =  DriverManager.getConnection("jdbc:mysql://localhost:3306/weixin","root","130145162");
        } catch (SQLException e) {

            e.printStackTrace();
        }catch(ClassNotFoundException e1){
            e1.printStackTrace();
        }
        return conn;
    }

    public static Statement createStmt(Connection conn){
        Statement stmt  = null;
        try {
            stmt = conn.createStatement();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        return stmt;

    }

    public static PreparedStatement prepareStmt(Connection conn,String sql) {
        PreparedStatement pstmt = null;
        try {
            pstmt = conn.prepareStatement(sql);
        } catch (SQLException e) {

            e.printStackTrace();
        }
        return pstmt;


    }

    public static PreparedStatement prepareStmt(Connection conn,String sql,int autoGeneratedKeys) {
        PreparedStatement pstmt = null;
        try {
            pstmt = conn.prepareStatement(sql,autoGeneratedKeys);
        } catch (SQLException e) {

            e.printStackTrace();
        }
        return pstmt;


    }
    public static ResultSet executeQuery(Statement stmt,String sql) {
        ResultSet rs = null;

        try {
            rs = stmt.executeQuery(sql);
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return rs;
    }



    public static int executeUpdate(Connection conn, String sql) {
        int ret = 0;
        Statement stmt = null;
        try {
            stmt = conn.createStatement();
            ret = stmt.executeUpdate(sql);
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            close(stmt);
        }
        return ret;
    }

    //	public static int executeUpdate(Connection conn,String sql) {
//		int ret = 0;
//		Statement stmt = null;
//		try {
//			stmt = conn.createStatement();
//			ret = stmt.executeUpdate(sql);
//		} catch (SQLException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}finally{
//			DB.close(stmt);
//		}
//		return ret;
//	}
//	
    public static void close(Connection conn) {
        if(conn != null) {
            try {
                conn.close();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    public static void close(Statement stmt) {
        if(stmt != null) {
            try {
                stmt.close();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

    public static void close(ResultSet rs) {
        if(rs != null) {
            try {
                rs.close();
            } catch (SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }

}
